# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: test

on:
  push:

jobs:
  publish:
    name: Publish docker image and binaries
    env:
      ARTIFACT_DIR: ./release
      DAPR_VERSION_ARTIFACT: dapr_version
    runs-on: ubuntu-latest
    steps:
      - name: import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: generate signed files
        run: gpg --armor --detach-sign README.md && ls -l
